"""
Generates PySpark notebook scripts (Fabric-notebook-ready) that create Delta
tables for each star-schema table and load them from the on-prem SQL Server
via a mirrored/staged source. These are provided as a deployable artifact
per the migration requirement to "develop scripts for the underlying tables
... for delta tables in Fabric" - i.e., something a Fabric engineer can open
directly in a Fabric notebook and run, independent of this tool's own
automated `datamover.loader` path (which writes Delta tables directly via
the `deltalake` library without needing Spark).

IMPORTANT / NOT ASSUMED: Fabric Spark notebooks cannot reach an on-prem SQL
Server directly unless one of the following is already in place - this tool
does NOT assume any of these exist:
  (a) An On-premises Data Gateway registered in the Fabric tenant, referenced
      via a Fabric data pipeline "Copy data" activity (not Spark) to stage
      the source rows into Files/ as Parquet first, or
  (b) Database Mirroring configured for the on-prem SQL Server (requires
      SQL Server 2025 + Fabric mirroring configured), or
  (c) The extracted Parquet files are uploaded to the Lakehouse Files/ area
      by some other process (e.g. this tool's own loader, run from a
      network location that can reach the on-prem server) before the
      notebook runs.
The generated notebook therefore reads from a Files/staging/<table>/*.parquet
path and writes a managed Delta table - it does NOT attempt a live JDBC
connection to the on-prem SQL Server from inside Fabric.
"""
from __future__ import annotations

import json
import os

AMO_TO_SPARK_TYPE = {
    "System.Int32": "IntegerType()",
    "System.Int16": "ShortType()",
    "System.Int64": "LongType()",
    "System.Double": "DoubleType()",
    "System.Single": "FloatType()",
    "System.Decimal": "DecimalType(18,2)",
    "System.String": "StringType()",
    "System.DateTime": "TimestampType()",
    "System.Boolean": "BooleanType()",
}


def _table_columns_ir(ir, table_name):
    for dsv in ir.get("data_source_views", []):
        for t in dsv.get("tables", []):
            if t["name"] == table_name:
                return t["columns"]
    return []


def generate_notebook_script(ir, table_name):
    columns = _table_columns_ir(ir, table_name)
    schema_fields = ",\n".join(
        f'    StructField("{c["name"]}", {AMO_TO_SPARK_TYPE.get(c["data_type"], "StringType()")}, True)'
        for c in columns
    )
    return f'''# Fabric notebook cell: create/refresh Delta table "{table_name}"
# Auto-generated by ssas_fabric_migrator. See module docstring for staging
# path assumptions - update `staging_path` below to match your actual
# gateway/mirroring/upload mechanism before running.

from pyspark.sql.types import (
    StructType, StructField, IntegerType, ShortType, LongType, DoubleType,
    FloatType, DecimalType, StringType, TimestampType, BooleanType,
)

schema = StructType([
{schema_fields}
])

staging_path = "Files/staging/{table_name}/"  # TODO: confirm this matches your upload location

df = spark.read.schema(schema).parquet(staging_path)

df.write.format("delta").mode("overwrite").saveAsTable("{table_name}")

print(f"Loaded {{df.count()}} rows into Delta table {table_name}")
'''


def generate_all_notebook_scripts(ir, output_dir):
    written = []
    for dsv in ir.get("data_source_views", []):
        for t in dsv.get("tables", []):
            table_name = t["name"]
            script = generate_notebook_script(ir, table_name)
            path = os.path.join(output_dir, f"create_{table_name}.py")
            os.makedirs(output_dir, exist_ok=True)
            with open(path, "w", encoding="utf-8", newline="\n") as f:
                f.write(script)
            written.append(path)
    return written


if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="Generate Fabric notebook Delta table creation scripts")
    parser.add_argument("--metadata", default="output/cube_metadata.json")
    parser.add_argument("--output", default="output/notebooks")
    args = parser.parse_args()

    with open(args.metadata, "r", encoding="utf-8") as f:
        ir = json.load(f)

    paths = generate_all_notebook_scripts(ir, args.output)
    for p in paths:
        print(f"Wrote {p}")
